include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - ios/Flutter/.symlinks/**
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false

linter:
  rules:
    - avoid_print
    - prefer_single_quotes
    - cancel_subscriptions
    - close_sinks
    - always_use_package_imports

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
